version: "3"

services:
  backend:
    image: ghcr.io/k4czp3r/dutch-fuel-prices-api:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8180:1337"
  mongo:
    image: mongo
    ports:
      - "27017:27017"